version: "3.9"

services:
  tomcat:
    build: .
    container_name: tomcat-app
    ports:
      - "8080:8080"
    environment:
      TZ: America/Santiago
    volumes:
      # Carpeta para guardar logs de Tomcat en tu m√°quina local
      - ./logs:/usr/local/tomcat/logs
    restart: no
